apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-script
data:
  initdb.sh: |-
   #!/bin/bash
   set -e
   psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER maxir WITH PASSWORD 'maxir';
    CREATE DATABASE dbapp;
    GRANT ALL PRIVILEGES ON DATABASE dbapp TO maxir;
   EOSQL
