apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 5Gi
  accessModes:
    #- ReadWriteMany
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data"


