name: CI

on:
  push:
    branches: 
      - 'releases/**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tar -cvf my-pack.tar .
      - name: Upload my artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact 
          path: my-pack.tar