name: CI

on:
  push:
    branches: 
      - 'realeases/**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Esto es una mensaje de prueba." > test.txt
      - name: Upload my artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact 
          path: test.txt