name: CI

on:
  push:
    branches: 
      - 'releases/**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd /home/maxi/DevOps/kubernetes/
          cp FactuTest Factu
          echo "Project packaging." > Factu/test.txt
      - name: Upload my artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact 
          path: Factu