name: CI test

on:
  push:    
    tags:
      - "v*.*.*"
      
env:
  DOCKERHUB_REPO: maxirobledo/factutest

jobs:
  creator:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/checkout@v2      

      - name: Build
        #id: release
        uses: softprops/action-gh-release@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:latest 
          #${{ env.DOCKERHUB_REPO }}:${{ steps.release.tag_name }}
          



  