name: CI test

on:
  push:    
    tags:
      - "v*.*.*"
      
env:
  DOCKERHUB_REPO: maxirobledo/factutest

jobs:
  creator:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/checkout@v2      

      - name: Build
        id: builder
        if: startsWith(github.ref, '')
        uses: softprops/action-gh-release@v1

      - name: Show
        run: |
            echo repo : ${{ env.DOCKERHUB_REPO }}
            echo GITHUB REG : ${{ github.ref }}
            echo upload_url : ${{ steps.builder.outputs.upload_url }}
            echo id realease : ${{ steps.builder.outputs.id }}


      #- name: Login to DockerHub
        #uses: docker/login-action@v1 
        #with:
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_TOKEN }}

      #- name: Build and Push to DockerHub
        #uses: docker/build-push-action@v2
        #with:
          #push: true
          #tags: ${{ env.DOCKERHUB_REPO }}:${{ steps.builder.tag_name }}
          



  