name: CI
on:
  push:    
    tags:
      - "v*.*.*"
env:
  DOCKERHUB_REPO: maxirobledo/factutest
jobs:
  creator:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2      

      - name: Build
        id: builder
        uses: softprops/action-gh-release@v1
        with:
          name: "$maxi"
        env:
          TAG: "steps.builder.tag_name"
        
      - name: Show
        run: |
          echo "TAG = ${{github.ref}}"
          echo "TAG = ${{ github.event.release.tag_name }}"
          echo "URL = ${{steps.builder.outputs.url}}"
          echo "ID VERSION = ${{steps.builder.outputs.id}}"
          echo "UPLOAD URL = ${{steps.builder.outputs.upload_url}}"
          echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"
          echo "${GITHUB_REF##*/}"
          echo "::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)"
          echo "${{ steps.get_version.outputs.VERSION }}"
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}


      #- name: Login to DockerHub
        #uses: docker/login-action@v1 
        #with:
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_TOKEN }}

      #- name: Build and Push to DockerHub
        #uses: docker/build-push-action@v2
        #with:
          #push: true
          #tags: ${{ env.DOCKERHUB_REPO }}:${{ steps.builder.tag_name }}

          
          

            
     