name: CI
on:
  push:    
    tags:
      - "v*.*.*"
env:
  DOCKERHUB_REPO: maxirobledo/factutest
  #TAG: ${GITHUB_REF/refs\/tags\//}
jobs:
  creator:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2      

      - name: Build
        id: builder
        uses: softprops/action-gh-release@v1

      - name: Generator
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS='["user/image:latest","user/image:'${GITHUB_REF/refs\/tags\//}'"]'
          else
            TAGS='["user/image:latest"]'
          fi
          echo '::set-output name=tags::'$TAGS
    
      #- name: Show
        #run: |
          ##echo "TAG - ${GITHUB_REF##*/}"          
          #echo "TAG - ${GITHUB_REF/refs\/tags\//}"
          #echo "ENV - ${{env.TAG}}"

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          #tags: ${{env.DOCKERHUB_REPO}}:$TAG
          tags: ${{ fromJson(steps.gen_tags.outputs.tags) }}
    
     