name: Comment
on:
  issue_comment:
    types: [created]
    
env:
  DOCKERHUB_REPO: maxirobledo/factutest

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
        
        if: contains(github.event.comment.body, '/rebuild')
      - name: Verify
        run: echo "El comentario ${{ github.event.comment.body }}  se encuentra"
      
      #- name: Docker metadata
        #id: metadata
        #uses: docker/metadata-action@v3
        #with:
          #images: ${{env.DOCKERHUB_REPO}}        
          #tags: ${{ steps.get_version.outputs.VERSION }}

      #- name: Login to DockerHub
        #uses: docker/login-action@v1 
        #with:
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_TOKEN }}        
      
        #if: contains(github.event.comment.body, 'rebuild')
      #- name: Build and Push to DockerHub
        #uses: docker/build-push-action@v2
        #with:
          #context: .
          #push: true          
          #tags: ${{ steps.metadata.outputs.tags }}
