name: Comment
on:
  issue_comment:
    types: [created, edited, deleted]
    
env:
  DOCKERHUB_REPO: maxirobledo/factutest
  #BODY: ${{ github.event.comment.body }}

jobs:
  verify:
    if: contains(github.event.comment.body, '!rebuild')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
              
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{env.DOCKERHUB_REPO}}        
          tags: ${{ steps.get_version.outputs.VERSION }}

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        
      
      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true          
          tags: ${{ steps.metadata.outputs.tags }}
