name: Release manual

on:
  #workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
      
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/checkout@v2      
      - name: Build
        uses: softprops/action-gh-release@v1
        #with:
          #draft: false
          #prerelease: false
          #name: ${{ steps.version.outputs.version }}
          #token: ${{ github.token }}

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: maxirobledo/factutest:latest




  