name: test
on:
  pull_request:
    types: 
      - opened 
      - reopened
    #branches:
      #- main
jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:       
      - run: |
          echo "Hello world!"
          echo "Today is $(date)"
